name: dorm_client
description: An easy-to-use Dart client for interacting with multiple DORM APIs.
version: 0.0.8
homepage: https://www.kirtz.eu
repository: https://github.com/svki0001/DORM-Dart-Client

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dio: ^5.0.3
  json_annotation: ^4.8.0
